### ISSUE TITLE
Add FilterHandler (or similar) and then apply sequencing capability

### ISSUE THREAD

**Issue by t8dogg** [GoogleCloudPlatform/market-data-transcoder#115]
@t8dogg I agree with that but would suggest maybe tracking that under another issue. I think we''d do a FilterHandler or similar then apply the sequencing capability. Will open under separate issue.

_Originally posted by @salsferrazza in https://github.com/GoogleCloudPlatform/market-data-transcoder/pull/114#discussion_r1131177884_

**Comment by salsferrazza** [comment]
fixed via #129
