### ISSUE TITLE
Key Error for certain SBE schemas/files introduced in Pull #89

### ISSUE THREAD

**Issue by t8dogg** [GoogleCloudPlatform/market-data-transcoder#147]
Prior to Pull #89, the Transcoder ran successfully the following command:

`python3 main.py    --factory cme   --schema_file transcoder/cme/templates_FixBinary_v12.xml   --source_file transcoder/cme/314-20221007-e --source_file_format_type cme_binary_packet   --message_skip_bytes 2   --source_file_endian little   --output_type avro --message_type_inclusions SecurityTradingEvent`

Following that PR, the Transcoder throws an error ending in:

```
File "/usr/local/google/home/matait/code/market-data-transcoder/third_party/sbedecoder/message.py", line 623, in wrap
    group_offset += group.wrap(msg_buffer, msg_offset, group_offset)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/matait/code/market-data-transcoder/third_party/sbedecoder/message.py", line 542, in wrap
    block_length = self.block_length_field.value
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/matait/code/market-data-transcoder/third_party/sbedecoder/message.py", line 282, in value
    _raw_value = self.raw_value
                 ^^^^^^^^^^^^^^
  File "/usr/local/google/home/matait/code/market-data-transcoder/third_party/sbedecoder/message.py", line 318, in raw_value
    _, primitive_type_size = TypeMap.primitive_type_map[self.primitive_type]
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
```

**Comment by salsferrazza** [comment]
this also affects the `pcap.sh` script in `examples/bin`

**Comment by mservidio** [comment]
This is broken because block_length type message doesn't contain a primitive type. Additionally, at some point we excluded processing schemas that contain zero fields, I think this was mainly for persistence to databases, etc.

**Comment by mservidio** [comment]
See for a work-around, but this needs to be further tested.

https://github.com/GoogleCloudPlatform/market-data-transcoder/compare/main...%23147
