### ISSUE TITLE
Automatically handle b64url decoding

### ISSUE THREAD

**Issue by salsferrazza** [GoogleCloudPlatform/market-data-transcoder#44]
The current `--base64` decoding capability doesn't automatically handle [b64url](https://www.base64url.com/) decoding of payloads. Some systems, such as Pub/Sub, return message payloads as base64url decoded strings (which are safe for use in URLs and filenames). The transcoder should detect from the payload contents and use the proper codec.

Currently, in order to properly decode a Pub/Sub message payload delivered by `gcloud` CLI, the b64url encoding needs to be explicitly replaced with b64 classic equivalents, for example:

```
gcloud pubsub subscriptions pull ${SUBSCRIPTION_NAME}  --format=json | json -a .message.data | tr '_' '/' | tr '-' '+'
```

Without the `tr` on the` message.data` string returned from Pub/Sub, the transcoder will fail to base64 decode the original message bytes.

**Comment by mservidio** [comment]
https://docs.python.org/3/library/base64.html
base64.urlsafe_b64decode(s)
